version: "3.9"

services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=employee_management
      - DB_USER=postgres
      - DB_PASSWORD=postgres

  db:
    image: postgres:13
    ports:
      - "54324:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: employee_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  # Optionally, add a Redis service for caching, Celery, etc.
  # redis:
  #   image: redis:alpine

volumes:
  postgres_data:
